/*
 * @lc app=leetcode id=389 lang=java
 *
 * [389] Find the Difference
 *
 * https://leetcode.com/problems/find-the-difference/description/
 *
 * algorithms
 * Easy (53.03%)
 * Likes:    493
 * Dislikes: 227
 * Total Accepted:    144K
 * Total Submissions: 271.5K
 * Testcase Example:  '"abcd"\n"abcde"'
 *
 * 
 * Given two strings s and t which consist of only lowercase letters.
 * 
 * String t is generated by random shuffling string s and then add one more
 * letter at a random position.
 * 
 * Find the letter that was added in t.
 * 
 * Example:
 * 
 * Input:
 * s = "abcd"
 * t = "abcde"
 * 
 * Output:
 * e
 * 
 * Explanation:
 * 'e' is the letter that was added.
 * 
 */
package Java;

class Solution389 {
    public char findTheDifference(String s, String t) {
        int num = 0;
        for (int i = 0; i < s.length(); i++) {
            num ^= s.charAt(i) - 'a';
        }
        for (int i = 0; i < t.length(); i++) {
            num ^= t.charAt(i) - 'a';
        }
        return (char) (num + 'a');
    }
}